[package]
name = "mm2_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
fomat-macros.workspace = true
gstuff.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
base64 = "0.10.0"
futures.workspace = true
hdrhistogram = { version = "7.0", default-features = false, features = ["sync"] }
http.workspace = true
hyper = { version = "0.14.11", features = ["server", "http1", "tcp"] }
itertools.workspace = true
