#!/bin/bash
source userpass
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"MARTY\",\"servers\":[{\"url\":\"marty.electrum1.cipig.net:10021\"},{\"url\":\"marty.electrum2.cipig.net:10021\"},{\"url\":\"marty.electrum3.cipig.net:10021\"}]}"
