#!/bin/bash
source userpass
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"DOC\",\"servers\":[{\"url\":\"doc.electrum1.cipig.net:10020\"},{\"url\":\"doc.electrum2.cipig.net:10020\"},{\"url\":\"doc.electrum3.cipig.net:10020\"}]}"
