[package]
name = "proxy_signature"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
chrono.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libp2p = { workspace = true, features = ["secp256k1", "ed25519", "tcp", "tokio"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
libp2p = { workspace = true, features = ["secp256k1", "ed25519", "wasm-ext"] }

[dev-dependencies]
rand = { version = "0.8", features = ["std", "small_rng"] }
